packages:
  - apps/playground2

ignoredBuiltDependencies:
  - lmdb
  - sharp

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - nx
patchedDependencies:
  '@nx/devkit': patches/@nx__devkit.patch
