packages:
  - apps/playground2

allowBuilds:
  nx: true
  unrs-resolver: false

ignoredBuiltDependencies:
  - lmdb
  - sharp

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - nx
patchedDependencies:
  '@nx/devkit': patches/@nx__devkit.patch
