export const ICON_MAP: Record<string, string> = {
  akar: '@ng-icons/akar-icons',
  bootstrap: '@ng-icons/bootstrap-icons',
  circum: '@ng-icons/circum-icons',
  crypto: '@ng-icons/cryptocurrency-icons',
  css: '@ng-icons/css.gg',
  drip: '@ng-icons/dripicons',
  feather: '@ng-icons/feather-icons',
  game: '@ng-icons/game-icons',
  huge: '@ng-icons/huge-icons',
  iconoir: '@ng-icons/iconoir',
  ion: '@ng-icons/ionicons',
  jam: '@ng-icons/jam-icons',
  lucide: '@ng-icons/lucide',
  mat: '@ng-icons/material-icons/baseline',
  mono: '@ng-icons/mono-icons',
  oct: '@ng-icons/octicons',
  radix: '@ng-icons/radix-icons',
  remix: '@ng-icons/remixicon',
  simple: '@ng-icons/simple-icons',
  svgl: '@ng-icons/svgl',
  tdesign: '@ng-icons/tdesign-icons',
  typ: '@ng-icons/typicons',
  aspects: '@ng-icons/ux-aspects',
};
