name: "Setup coverage report"
description: "Setup coverage report"

inputs:
  path:
    required: true
    description: Path to covertura coverage path

runs:
  using: "composite"
  steps:
    - name: Copy Coverage to predictable Location
      run: cp ${{ inputs.path }} coverage/coverage.cobertura.xml
      shell: bash

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/coverage.cobertura.xml
        badge: true
        format: 'markdown'
        output: 'both'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
      shell: bash