import {Component} from '@angular/core';
import {HttpClient, HttpClientModule} from '@angular/common/http';
import {TestBed} from '@angular/core/testing';
import {DfxTranslateModule} from './dfx-translate.module';
import {TranslateService} from './translate.service';
import {serviceStub} from './test-helper';

@Component({
  template: ' <div>{{ translateKey | tr }}</div> ',
})
class TestTranslateDirectiveComponent {
  translateKey?: string;
}

describe('TranslateConfig', () => {
  let translateService: TranslateService;

  beforeEach(() => {
    localStorage.clear();

    void TestBed.configureTestingModule({
      declarations: [TestTranslateDirectiveComponent],
      imports: [DfxTranslateModule.setup()],
      providers: [{provide: HttpClient, useValue: serviceStub}],
    }).compileComponents();

    translateService = TestBed.inject(TranslateService);
  });

  it('should use default values', () => {
    expect(translateService.defaultLanguage).toBe('en');
    expect(translateService.getSelectedLanguage()).toBe('en');
    expect(translateService.useLocalStorage).toBeTruthy();
    expect(translateService.languagesWithAutoTranslation.length).toBe(0);
  });

  it('should language be defined', () => {
    expect(translateService.translations).not.toEqual({});
  });

  it('should autotranslated language be undefined', () => {
    expect(translateService.autoGeneratedTranslations).toEqual({});
  });

  it('should not store default language', () => {
    expect(localStorage.getItem('language')).toBeNull();
    expect(translateService.getSelectedLanguage()).toBe('en');
  });

  it('should store changed language as cookie', async () => {
    expect(translateService.getSelectedLanguage()).toBe('en');
    expect(localStorage.getItem('language')).toBeNull();
    await translateService.use('de');
    expect(localStorage.getItem('language')).toBeDefined();
    expect(localStorage.getItem('language')).toBe('de');
    expect(translateService.getSelectedLanguage()).toBe('de');
  });

  it('should change language via spy', async () => {
    const spy = jest.spyOn(translateService, 'use');
    await translateService.use('de');
    expect(spy).toHaveBeenCalledWith('de');
  });

  it('should change language', async () => {
    await translateService.use('de');
    expect(translateService.getSelectedLanguage()).toBe('de');
  });
});

describe('TranslateConfig2', () => {
  let translateService: TranslateService;

  beforeEach(() => {
    void TestBed.configureTestingModule({
      declarations: [TestTranslateDirectiveComponent],
      imports: [HttpClientModule, DfxTranslateModule.setup({languagesWithAutoTranslation: ['de'], assetsPath: 'assets/i18n/'})],
    }).compileComponents();

    localStorage.setItem('language', 'en');
    translateService = TestBed.inject(TranslateService);
  });

  it('should store changed language as cookie 2', async () => {
    expect(localStorage.getItem('language')).toBe('en');
    expect(translateService.getSelectedLanguage()).toBe('en');
  });

  it('should fail on loading language', async () => {
    await translateService.use('de');
    expect(translateService.translations).toEqual({});
  });
});

describe('TranslateConfigChanged', () => {
  let translateService: TranslateService;

  beforeEach(() => {
    localStorage.clear();

    void TestBed.configureTestingModule({
      declarations: [TestTranslateDirectiveComponent],
      imports: [
        DfxTranslateModule.setup({
          defaultLanguage: 'de',
        }),
      ],
      providers: [{provide: HttpClient, useValue: serviceStub}],
    }).compileComponents();

    translateService = TestBed.inject(TranslateService);
  });

  it('should use default values', () => {
    expect(translateService.defaultLanguage).toBe('de');
    expect(translateService.getSelectedLanguage()).toBe('de');
    expect(translateService.useLocalStorage).toBeTruthy();
    expect(translateService.languagesWithAutoTranslation.length).toBe(0);
  });

  it('should language be defined', () => {
    expect(translateService.translations).not.toEqual({});
  });

  it('should not store default language as cookie', () => {
    expect(localStorage.getItem('language')).toBeNull();
    expect(translateService.getSelectedLanguage()).toBe('de');
  });

  it('should store changed language as cookie', async () => {
    expect(localStorage.getItem('language')).toBeNull();
    await translateService.use('en');
    expect(localStorage.getItem('language')).toBe('en');
  });

  it('should change language via spy', async () => {
    const spy = jest.spyOn(translateService, 'use');
    await translateService.use('en');
    expect(spy).toHaveBeenCalledWith('en');
  });

  it('should change language', async () => {
    await translateService.use('de');
    expect(translateService.getSelectedLanguage()).toBe('de');
  });
});
