name: "Publish library"
description: "Publish library"

inputs:
  lib:
    required: true
    description: Lib name

runs:
  using: "composite"
  steps:
    - name: get version
      shell: bash
      run: |
        version=$(node -p "require('./projects/dfx-helper/package.json').version")
        echo $version

    - uses: actions/download-artifact@master
      with:
        name: ${{ inputs.lib }}
        path: ./dist
    - name: dist lookup
      shell: bash
      run: |
        cd dist
        ls -la
        cd -

    - name: zip ${{ inputs.lib }}.zip
      shell: bash
      run: zip -r "${{ inputs.lib }}.zip" ./dist >> /dev/null

    - name: copy ${{ inputs.lib }}-latest.zip to release server
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./${{ inputs.lib }}.zip
        remote: /var/www/datepoll-share/common/${{ inputs.lib }}/${{ inputs.lib }}-latest.zip
        host: ${{ secrets.RELEASES_SSH_HOST }}
        port: ${{ secrets.RELEASES_SSH_PORT }}
        username: ${{ secrets.RELEASES_SSH_USER }}
        privateKey: ${{ secrets.RELEASES_SSH_PRIVATE_KEY }}

    - name: copy ${{ inputs.lib }}-VERSION.zip to release server
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./${{ inputs.lib }}.zip
        remote: "/var/www/datepoll-share/common/${{ inputs.lib }}/${{ inputs.lib }}-v${version}.zip"
        host: ${{ secrets.RELEASES_SSH_HOST }}
        port: ${{ secrets.RELEASES_SSH_PORT }}
        username: ${{ secrets.RELEASES_SSH_USER }}
        privateKey: ${{ secrets.RELEASES_SSH_PRIVATE_KEY }}