import {Component, DebugElement} from '@angular/core';
import {HttpClient} from '@angular/common/http';
import {ComponentFixture, TestBed} from '@angular/core/testing';
import {DfxTranslateModule} from '../dfx-translate.module';
import {TranslateService} from '../translate.service';
import {serviceStub} from '../test-helper';

@Component({
  template: '<div>{{ translateKey | tr }}</div>',
})
class TestTranslateDirectiveComponent {
  translateKey?: string;
}

describe('TranslateDirective', () => {
  let component: TestTranslateDirectiveComponent;
  let fixture: ComponentFixture<TestTranslateDirectiveComponent>;
  let de: DebugElement;
  let translateService: TranslateService;

  beforeEach(() => {
    localStorage.clear();

    void TestBed.configureTestingModule({
      declarations: [TestTranslateDirectiveComponent],
      imports: [
        DfxTranslateModule.setup({
          useLocalStorage: false,
        }),
      ],
      providers: [{provide: HttpClient, useValue: serviceStub}],
    }).compileComponents();

    translateService = TestBed.inject(TranslateService);

    fixture = TestBed.createComponent(TestTranslateDirectiveComponent);
    component = fixture.componentInstance;
    de = fixture.debugElement;

    fixture.detectChanges();
  });

  it('should use configured values', () => {
    expect(translateService.defaultLanguage).toBe('en');
    expect(translateService.getSelectedLanguage()).toBe('en');
    expect(translateService.languagesWithAutoTranslation.length).toBe(0);
    expect(translateService.useLocalStorage).toBeFalsy();
    expect(localStorage.getItem('language')).toBeNull();
  });

  it('should create an instance', () => {
    expect(component).toBeTruthy();
  });

  it('should return undefined', () => {
    expect((fixture.nativeElement as HTMLElement).querySelector('div')?.textContent).toBe('undefined');
  });

  it('should return key', () => {
    component.translateKey = 'key';
    fixture.detectChanges();
    expect((fixture.nativeElement as HTMLElement).querySelector('div')?.textContent).toBe('key');
  });

  it('should return value', () => {
    component.translateKey = 'testkey1';
    fixture.detectChanges();
    expect((fixture.nativeElement as HTMLElement).querySelector('div')?.textContent).toBe('testanswer1');
  });

  it('should return other value', () => {
    component.translateKey = 'testkey2';
    fixture.detectChanges();
    expect((fixture.nativeElement as HTMLElement).querySelector('div')?.textContent).toBe('testanswer2');
  });

  it('should return value after selecting other language', () => {
    component.translateKey = 'testkey1';
    translateService.use('de');
    fixture.detectChanges();
    expect((fixture.nativeElement as HTMLElement).querySelector('div')?.textContent).toBe('testanswer1_DE');
  });

  it('should return other value after selecting other language', () => {
    component.translateKey = 'testkey2';
    translateService.use('de');
    fixture.detectChanges();
    expect((fixture.nativeElement as HTMLElement).querySelector('div')?.textContent).toBe('testanswer2_DE');
  });
});

describe('TranslateDirectiveWithAuto', () => {
  let component: TestTranslateDirectiveComponent;
  let fixture: ComponentFixture<TestTranslateDirectiveComponent>;
  let de: DebugElement;
  let translateService: TranslateService;

  beforeEach(() => {
    localStorage.clear();

    void TestBed.configureTestingModule({
      declarations: [TestTranslateDirectiveComponent],
      imports: [
        DfxTranslateModule.setup({
          useLocalStorage: false,
          languagesWithAutoTranslation: ['de'],
        }),
      ],
      providers: [{provide: HttpClient, useValue: serviceStub}],
    }).compileComponents();

    translateService = TestBed.inject(TranslateService);

    fixture = TestBed.createComponent(TestTranslateDirectiveComponent);
    component = fixture.componentInstance;
    de = fixture.debugElement;

    fixture.detectChanges();
  });

  it('should use configured values', () => {
    expect(translateService.defaultLanguage).toBe('en');
    expect(translateService.getSelectedLanguage()).toBe('en');
    expect(translateService.languagesWithAutoTranslation.length).toBe(1);
    expect(translateService.useLocalStorage).toBeFalsy();
    expect(localStorage.getItem('language')).toBeNull();
  });

  it('should autotranslated language be defined', () => {
    expect(translateService.autoGeneratedTranslations).toEqual({});
    translateService.use('de');
    expect(translateService.autoGeneratedTranslations).not.toEqual({});
  });

  it('should return undefined with auto generated', () => {
    expect((fixture.nativeElement as HTMLElement).querySelector('div')?.textContent).toBe('undefined');
  });

  it('should return key with auto generated', () => {
    component.translateKey = 'key';
    fixture.detectChanges();
    expect((fixture.nativeElement as HTMLElement).querySelector('div')?.textContent).toBe('key');
  });

  it('should return value', () => {
    component.translateKey = 'testkey1';
    fixture.detectChanges();
    expect((fixture.nativeElement as HTMLElement).querySelector('div')?.textContent).toBe('testanswer1');
  });

  it('should return other value', () => {
    component.translateKey = 'testkey2';
    fixture.detectChanges();
    expect((fixture.nativeElement as HTMLElement).querySelector('div')?.textContent).toBe('testanswer2');
  });

  it('should return autogenerated value', () => {
    component.translateKey = 'testkey4';
    fixture.detectChanges();
    expect((fixture.nativeElement as HTMLElement).querySelector('div')?.textContent).toBe('testanswer4');
  });

  it('should return value after selecting other language', () => {
    component.translateKey = 'testkey1';
    translateService.use('de');
    fixture.detectChanges();
    expect((fixture.nativeElement as HTMLElement).querySelector('div')?.textContent).toBe('testanswer1_DE');
  });

  it('should return autogenerated value after selecting other language', () => {
    component.translateKey = 'testkey4';
    translateService.use('de');
    fixture.detectChanges();
    expect((fixture.nativeElement as HTMLElement).querySelector('div')?.textContent).toBe('testanswer4_DE_auto');
  });

  it('should return other value after selecting other language', () => {
    component.translateKey = 'testkey2';
    translateService.use('de');
    fixture.detectChanges();
    expect((fixture.nativeElement as HTMLElement).querySelector('div')?.textContent).toBe('testanswer2_DE');
  });
});
