name: release dfx-translate

on:
  push:
    tags:
      - 'dfx-translate*'

jobs:
  dfx-translate:
    uses: dafnik/dfts-common/.github/workflows/release.yml@develop
    with:
      lib: dfx-translate
    secrets: inherit